config/routes.rb
Mydog::Application.routes.draw do

  root :to => 'Lists#index'
  get "/lists" => 'Lists#index', :as => :lists

  post "/reddits/:id" => 'Reddits#postcomment', :as => :comment
  get "/fbooks/seed" => 'Fbooks#seed', :as => :fbooks_seed
  get "/imgurls/seed" => 'Imgurls#seed', :as => :imgurls_seed

  resources :imgurls, :only => [:index, :create, :destroy]
  resources :fbooks, :only => [:index, :new, :create, :destroy]
  resources :reddits, :only => [:index, :new, :create]

end

app/models/fbook.rb
class Fbook < ActiveRecord::Base
  attr_accessible :access, :url




end

app/models/imgurl.rb
class Imgurl < ActiveRecord::Base
  attr_accessible :url

	# require 'open-uri'

  def api
    File.open('C:\Sites\dev\imgur_api.txt').readline.to_s
  end

	def upload(key, file_path)
	  url        = "http://imgur.com/api/upload.json"
	  data       = {
	    :key     => key, :image => open(file_path)
	  }

	  response   = RestClient.post(url, data)
	  imgur_url  = JSON.parse(response.body)["rsp"]["image"]["original_image"] rescue nil
	end

end

app/models/reddit.rb
class Reddit < ActiveRecord::Base
  attr_accessible :url

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :access
  def access
  	''
  end

end

app/controllers/fbooks_controller.rb
class FbooksController < ApplicationController
  require 'open-uri'

  def seed
    @fbooks = Fbook.all
    filename = 'fbseed.txt'

    open(filename, 'w') do |f|
      @fbooks.each do |hash|
        f.puts "#{hash['url']} #{hash['inimgur']}"
      end      
    end

    redirect_to fbooks_url
  end

  def index
    @fbooks = Fbook.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @fbook = Fbook.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    # 2011 album url = "https://graph.facebook.com/272989652716535/photos?access_token=#{access}&limit=200"
    # 2012 album
    @fbook = Fbook.new(params[:fbook])
    access = @fbook.access
    url = "https://graph.facebook.com/373528459329320/photos?access_token=#{access}&limit=200"

    response = open(url).read
    json_response = JSON.parse(response)
    @posts = json_response["data"]      
    newfb = @posts.select { |post| post["images"].present? }

    @fbooks = Fbook.all
    newfb.each do |nfb|
      flag = 0
      @fbooks.each do |fbs|
        if nfb["source"] == fbs.url
          flag = 1
          break
        end
      end
      if flag == 0
        @fbook = Fbook.new
        @fbook.url = nfb["source"]
        @fbook.save
      end
    end

    respond_to do |format|
      if @fbook.present? && @fbook.save
        format.html { redirect_to fbooks_url, notice: 'Fbook was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    @fbook = Fbook.find(params[:id])
    @fbook.destroy

    respond_to do |format|
      format.html { redirect_to fbooks_url }
    end
  end

end

app/controllers/imgurls_controller.rb
class ImgurlsController < ApplicationController

  def seed
    @imgurls = Imgurl.all
    filename = 'imgurseed.txt'

    open(filename, 'w') do |f|
      @imgurls.each do |hash|
        f.puts "#{hash['url']}"
      end      
    end

    redirect_to imgurls_url
  end

  def index
    @imgurls = Imgurl.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def create
    @fbooks = Fbook.find_all_by_inimgur(false)
    if @fbooks.empty?
      redirect_to :back
    else
      @fbooks.each do |fb|
        @imgurl = Imgurl.new
        @imgurl.url = @imgurl.upload(@imgurl.api, fb.url)
        @imgurl.save
        fb.inimgur = true
        fb.save
      end

      respond_to do |format|
        if @imgurl.save
          format.html { redirect_to imgurls_url, notice: 'Imgurl was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    end
  end

  def destroy
    @imgurl = Imgurl.find(params[:id])
    @imgurl.destroy

    respond_to do |format|
      format.html { redirect_to imgurls_url }
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	def index
	end

end

app/controllers/reddits_controller.rb
class RedditsController < ApplicationController
  
  def defaultsearch
    url = "http://www.reddit.com/search.json?q=dog+reddit%3Afunny+OR+reddit%3Apics&sort=new&restrict_sr=off"
    getresponse(url)
  end

  def customsearch(subreddit)
    url = "http://www.reddit.com/search.json?q=dog+reddit%3A#{subreddit}&sort=new&restrict_sr=off"
    getresponse(url)
  end

  def getresponse(url)
    response = RestClient.get(url)
    reddit = JSON.parse(response.body, :max_nesting => false) rescue nil
    reddit = reddit["data"]["children"]
    reddit_url = []
    c = 0   
    reddit.count.times do |r|
      if Time.at(reddit[r]["data"]["created_utc"]).to_datetime > Time.now-100000
        reddit_url[c] = reddit[r]["data"]
        c += 1
      end
    end

    return reddit_url
  end
 
 def postcomment
    @reddit = Reddit.find_by_id(params[:id])
    @imgurls = Imgurl.all
    @reddit.commented = true
    @reddit.save
    name = @reddit.name
    doggeh = @imgurls[rand(@imgurls.count)].url.split[0]

    pword = File.open('C:\Sites\dev\reddit_api.txt').readline.to_s
    userhash = { 'user' => 'thatlookslikemydog', 'passwd' => pword, 'api_type' => 'json' }
    headers = { 'user-agent' => 'Thatlookslikemydog dog finder app' }
    url = 'https://ssl.reddit.com/api/login'    
    response = RestClient.post url, userhash, headers
    respjson = JSON.parse(response)
    modhash = respjson["json"]["data"]["modhash"]

    posturl = "http://www.reddit.com/api/comment"
    cookie = response.headers[:set_cookie]
    postheaders = { :cookie => cookie, 'user-agent' => 'Thatlookslikemydog dog finder app' }
    posting = { 'parent' => name, 'text' => "Hey, that looks like my dog! #{doggeh}", 'uh' => modhash, 'api_type' => 'json' }
    postresponse = RestClient.post posturl, posting, :cookie => cookie  #postheaders

    redirect_to reddits_url
  end

  def index
    @reddits = Reddit.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @reddit = Reddit.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    params.empty? ? reddit_list = customsearch(:url) : reddit_list = defaultsearch
    reddit_list.count.times do |list|
      @reddit = Reddit.new
      @reddit.url = reddit_list[list]["permalink"]
      @reddit.name = reddit_list[list]["name"]
      @reddit.img = reddit_list[list]["url"]
      ((reddit_list[list]["url"].split.last.length <= 4) && (reddit_list[list]["url"].include? 'imgur')) ? @reddit.img = reddit_list[list]["url"] : @reddit.img = reddit_list[list]["url"] + '.jpg'
      @reddit.save
    end

    oldest = Reddit.last.id-100
    if oldest > 1
      Reddit.destroy_all("id <= #{oldest}")
    end

    respond_to do |format|
      if @reddit.save
        format.html { redirect_to reddits_url, notice: 'Reddit was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fbooks_helper.rb
module FbooksHelper
end

app/helpers/imgurls_helper.rb
module ImgurlsHelper
end

app/helpers/reddits_helper.rb
module RedditsHelper

 #  def defaultsearch
 #  	url = "http://www.reddit.com/search.json?q=dog+reddit%3Afunny+OR+reddit%3Apics&sort=new&restrict_sr=off"
 #  	getresponse(url)
 #  end

 #  def customsearch(subreddit)
 #  	url = "http://www.reddit.com/search.json?q=dog+reddit%3A#{subreddit}&sort=new&restrict_sr=off"
 #  	getresponse(url)
 #  end

 #  def getresponse(url)
 #  	response = RestClient.get(url)
	# 	reddit = JSON.parse(response.body, :max_nesting => false) rescue nil
	# 	reddit = reddit["data"]["children"]
	# 	reddit_url = []
	# 	c = 0		
	# 	reddit.count.times do |r|
	# 		if helper.time_ago_in_words(Time.at(r["data"]["created_utc"]).to_datetime) > "12 hours"
	# 			reddit_url[c] = reddit[r]["data"]
	# 			c += 1
	# 		end
	# 	end

	# 	return reddit_url
	# end


end

app/views/fbooks/_branched.html.erb
<%= link_to "Check for new Facebook images", new_fbook_url %> | <%= link_to "Imgur side of things", imgurls_url %> | <%= link_to "Reddit side of things", reddits_url %> | <%= link_to "Create Facebook seed file", fbooks_seed_url %>

<br><br>

app/views/fbooks/_form.html.erb
To obtain access token, go to <a href="https://developers.facebook.com/tools/explorer/?method=GET&path=373528459329320%2Fphotos">https://developers.facebook.com/tools/explorer/?method=GET&path=373528459329320%2Fphotos</a> and click 'Get Access Token.' Make sure 'User Photos' is selected. Paste the access token below.
<br><br>
<%= form_for(@fbook) do |f| %>
  <% if @fbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fbook.errors.count, "error") %> prohibited this fbook from being saved:</h2>

      <ul>
      <% @fbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :access %><br />
    <%= f.text_field :access %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fbooks/edit.html.erb
<h1>Editing fbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @fbook %> |
<%= link_to 'Back', fbooks_path %>

app/views/fbooks/index.html.erb
<h1>Listing fbooks</h1>

<%= render 'branched' %>

<%= @fbooks.count %> pictures
<br>
<table>
  <br>
  <tr>
    <th>Image</th>
    <th>Url</th>
    <th></th>
  </tr>

<% @fbooks.each do |fbook| %>
  <tr>
    <td><img src="<%= fbook.url %>" height="100"></td>
    <td><%= fbook.url %></td>
    <td><%= link_to 'Destroy', fbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= render 'branched' %>

app/views/fbooks/new.html.erb
<h1>New fbook</h1>

<%= render 'form' %>

<%= link_to 'Back', fbooks_path %>

app/views/fbooks/seed.html.erb
UNDER CONSTRUCTION

app/views/fbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @fbook.url %>
</p>

<p>
<img src="<%= @fbook.url %>" /></a>
</p>


<%= link_to 'Edit', edit_fbook_path(@fbook) %> |
<%= link_to 'Back', fbooks_path %>

app/views/imgurls/_branched.html.erb
<%= link_to "Upload all new links to Imgur", imgurls_path, :method => :post %> | <%= link_to "Facebook side of things", fbooks_url %> | <%= link_to "Reddit side of things", reddits_url %> | <%= link_to "Create Imgur seed file", imgurls_seed_url %>

<br><br>

app/views/imgurls/_form.html.erb
<%= form_for(@imgurl) do |f| %>
  <% if @imgurl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imgurl.errors.count, "error") %> prohibited this fbook from being saved:</h2>

      <ul>
      <% @imgurl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imgurls/edit.html.erb
<h1>Editing imgurl</h1>

<%= render 'form' %>

<%= link_to 'Show', @imgurl %> |
<%= link_to 'Back', imgurls_path %>

app/views/imgurls/index.html.erb
<h1>Listing Imgur pics</h1>

<%= render 'branched' %>

<%= @imgurls.count %> pictures
<table>
  <tr>
    <th>Url</th>
    <th></th>
  </tr>

<% @imgurls.each do |imgurl| %>
  <tr>
    <td><img src="<%= imgurl.url %>" height="100"></td>
    <td><%= imgurl.url %></td>
    <td><%= link_to 'Destroy', imgurl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= render 'branched' %>

app/views/imgurls/new.html.erb
<h1>New imgurl</h1>

  <!-- <#%= render 'form' %> -->

<%= link_to 'Back', imgurls_path %>

app/views/imgurls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @imgurl.url %>
</p>


<%= link_to 'Edit', edit_imgurl_path(@imgurl) %> |
<%= link_to 'Back', imgurls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mydog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1>That Looks Like My Dog!</h1>
<br>
<%= link_to "Facebook side of things", fbooks_url %> | <%= link_to "Imgur side of things", imgurls_path %> | <%= link_to "Reddit side of things", reddits_url %>
<br>

app/views/reddits/_branched.html.erb
<%= link_to "Facebook side of things", fbooks_url %> | <%= link_to "Imgur side of things", imgurls_url %>

<br><br>

app/views/reddits/_form.html.erb
<%= form_for(@reddit) do |f| %>
  <% if @reddit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reddit.errors.count, "error") %> prohibited this reddit from being saved:</h2>

      <ul>
      <% @reddit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %><BR>
  Enter Subreddit to search, or leave blank for default (/funny and /pics).
  <div class="field">
    
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reddits/edit.html.erb
<h1>Editing reddit</h1>

<%= render 'form' %>

<%= link_to 'Show', @reddit %> |
<%= link_to 'Back', reddits_path %>

app/views/reddits/index.html.erb
<h1>Listing Reddits</h1>

<%= link_to 'New Search', new_reddit_path %> | <%= render 'branched' %>


<%= @reddits.count %> threads listed.
<table>
  <tr>
    <th>Image</th>
    <th>Replied?</th>
    <th>REPLY!</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @reddits.each do |reddit| %>
    <tr>
      <td><img src="<%= reddit.img %>" height="100"> <%= link_to "http://www.reddit.com#{reddit.url}", "http://www.reddit.com#{reddit.url}" %></td>
      <td><%= reddit.commented %></td>
      
      <td><%= link_to 'REPLY!', comment_url(reddit.id), :method => "post" %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Search', new_reddit_path %> | <%= render 'branched' %>

app/views/reddits/new.html.erb
<h1>New reddit</h1>

<%= render 'form' %>

<%= link_to 'Back', reddits_path %>

app/views/reddits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @reddit.url %>
</p>


<%= link_to 'Edit', edit_reddit_path(@reddit) %> |
<%= link_to 'Back', reddits_path %>